print('Olá Mundo')
nome = input('Qual o seu nome?')
print(f'Olá {nome}')
idade = int(input('Qual a sua idade?'))
print(f'Você tem {idade} anos, correto!?')
print(f'Você se chama {nome} e tem \n {idade} anos.')
print(f'Você se chama {nome} e tem {idade} anos.')
n1 = int(input('Digite o 1° número:'))
n2 = int(input('Digite o 2° número:'))
print(f'A soma dos dois números escolhidos é igual a {n1 + n2}')
print(f'A subtração dos dois números é igual a {n1 - n2}')
print(f'A multiplicação dos dois números é igual a {n1 * n2}')
print(f'A divisão dos dois números é igual a {n1 / n2}')
print(f'O resto da divisão dos dois números é igual a {n1 % n2}')